apiVersion: v1
kind: Secret
metadata:
  name: paralelo-secrets
type: Opaque
stringData:
  database-url: "postgresql://neondb_owner:npg_PIGOVAYnR0t9@ep-curly-bar-aqrb7o5g-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  jwt-secret: "paralelo_utesa_jwt_secret_2024"
  sns-topic-arn: "arn:aws:sns:us-east-1:913407539509:paralelo-notifications"
